#server:
#  port: 9004
#spring:
#  application:
#    name: user-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    alibaba:
#      seata:
#        tx-service-group: my_tx_group
#  datasource:
#    url: jdbc:mysql://localhost:3306/bill?Unicode=true&useSSL=false&serverTimezone=GMT%2B&characterEncoding=utf8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    tomcat:
#      max-active: 20
#      initial-size: 1
#      max-wait: 60000
#      min-idle: 1
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 30000
#      validation-query: select 'x'
#      test-on-borrow: false
#      test-while-idle: true
#      test-on-return: false
#    dbcp2:
#      max-open-prepared-statements: 20
#      pool-prepared-statements: true
#  jpa:
#    open-in-view: false
#  rabbitmq:
#    host: localhost
#  zipkin:
#    base-url: http://127.0.0.1:9411/  #zipkin server 的请求地址
#    discovery-client-enabled: false  #让nacos把它当做一个URL，而不要当作为微服务
#  sleuth:
#    sampler:
#      probability: 1.0  #采样后的百分比
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0
#    jedis:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 200
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接超时时间（毫秒）
#    timeout: 30000
#  devtools:
#    restart:
#      enabled: true
#    #此为解决时间相差8小时的问题
#  jackson:
#    time-zone: GMT+8
#  resources:
#    static-locations: classpath:templates/*.html
#  mvc:
#    static-path-pattern: /**
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.atli.provider.com.atli.provider.dao
#
#  #打印mybatis语句
#logging:
#  level:
#    com.atli.provider.dao: debug
#    io:
#      seata: info
#pagehelper:
#  offset-as-page-num: true
#  row-bounds-with-count: true
#  reasonable: true
#  helper-dialect: mysql
#  support-methods-arguments: true
#feign:
#  hystrix:
#    enabled: false